### ISSUE TITLE
Make Key Captialization Consistent

### ISSUE THREAD

**Issue by bbb651** [OatsCG/Openmusic-Server-Specs#1]
First of all I want to say I massively appreciate this project (both the Openmusic app and OMDB), they are incredibly well thought out and made it really shows that you put a lot of effort into them, hopefully it'll get more recognition at some point, I think you should try posting it to more places I'm sure there are a lot of people looking for free and open source music players but it's currently very hard to discover (I tried to make a [hackernews submission](https://news.ycombinator.com/item?id=40806503), didn't get much traction though...)

I'm working on a rust crate for the api (client side) to hopefully make a desktop player at some point, and I've noticed the key names in the results have some weird inconsistencies with casing, here are some examples from `/query` on `server.openmusic.app`, with the first two being the most common:
- `AlbumType` is PascalCase
- `Profile_Photo` is PascalCase + snake_case
- `AlbumID` has the `D` uppercase
- `allArtists` is camelCase, and is not documented in this repo

I would personally prefer everything to be snake_case but I'm biased for rust and python, camelCase would also be fine but I would really appreciate `ID` being turned into `Id` to make it possible to automatically convert `album_id` -> `albumId` with serde (the serialization library used in the rust ecosystem).

**Comment by OatsCG** [comment]
Thanks for the input and your support! I’ll take this into consideration for the next update, but it’s possible that this will not be done since the Openmusic app will have compatibility issues.

**Comment by OatsCG** [comment]
I welcome you to make a desktop player, so long as it’s open source as to uphold the purpose of Openmusic :)
